name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Workflow uruchomi się, gdy będą zmiany na gałęzi main

jobs:
  build:
    runs-on: ubuntu-latest # Wybór maszyny do uruchomienia

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Krok, który umożliwia sprawdzenie kodu w repozytorium

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          export SSH_AUTH_SOCK=$(ls /tmp/ssh-*/agent.*)
          ssh-add ~/.ssh/id_ed25519

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2 # Użycie wtyczki do logowania w GHCR
        with:
          registry: ghcr.io # Rejestr, do którego następuje logowanie
          username: ${{ github.actor }} # Nazwa użytkownika GitHub
          password: ${{ secrets.GITHUB_TOKEN }} # Token do autoryzacji

      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build --ssh default -t ghcr.io/${{ github.repository }}:lab6 .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:lab6
